#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Takanosuke Fukasawa
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += eng(line)
    except:    
            ans += float(line)

print(ans)            
